import csv

quotes = [
    "I don’t know why people expect art to make sense. They accept the fact that life doesn’t make sense.",
    "The more unknowable the mystery, the more beautiful it is.",  
    "I like things that go into hidden, mysterious places, places I want to explore that are very disturbing. In that disturbing thing, there is sometimes tremendous poetry and truth.",  
    "The world is as you are.",  
    "We only dream of images we already have inside of us.",  
    "Ideas are like fish. If you want to catch little fish, you can stay in the shallow water. But if you want to catch the big fish, you’ve got to go deeper. Down deep, the fish are more powerful and more pure. They’re huge and abstract. And they’re very beautiful.",  
    "Negativity is the enemy of creativity.",  
    "What do you fear, most of all? The possibility that love may not be enough.",  
    "New mysteries. New day. Fresh doughnuts.",  
    "I’m not comfortable with words. I love images, and I love sounds, and I love feelings. I like the idea of intuition. I think a lot of things in life are understood that way. But you internalize these things; they don’t really pop out. Certain things are built inside – little areas of understanding. I feel that I live in darkness and confusion, and I’m trying, like we all are, to make some sort of sense of it.",  
    "In today’s world of fear and uncertainty, every child should have one class period a day to dive within himself and experience the field of silence – bliss – the enormous reservoir of energy and intelligence that is deep within all of us. This is the way to save the coming generation.",  
    "Mankind was not meant to suffer — bliss is our nature. The individual is cosmic. Let’s rock.",  
    "We think we understand the rules when we become adults but what we really experience is a narrowing of the imagination.",  
    "I like to make films because I like to go into another world. I like to get lost in another world. And film to me is a magical medium that makes you dream… allows you to dream in the dark. It’s just a fantastic thing, to get lost inside the world of film.",  
    "This whole world is wild at heart and weird on top.",  
    "The day you catch an idea you fall in love with, even a small one, is a beautiful day.",  
    "There is this unbounded, infinite, eternal, level, ocean, within every human being. Inner happiness comes with consciousness, bliss, intelligence comes with it. Creativity, love.",
    "Human beings have a potential and it has names like enlightenment or fulfilment, or liberation.",
    "True happiness is not out there, true happiness lies within.",
    "They say beauty is only skin deep but it’s this stuff coming from the inside, absolute vibrant consciousness, absolute bliss",  
    "The artist does not have to suffer to show suffering.",  
    "It’s so freeing, it’s beautiful in a way, to have a great failure, there’s nowhere to go but up.",  
    "Float with me in the world of ether.",  
    "We all have at least two sides. The world we live in is a world of opposites. And the trick is to reconcile those opposing things. I’ve always liked both sides. In order to appreciate one you have to know the other. The more darkness you can gather up, the more light you can see too.",  
    "Absurdity is what I like most in life.",  
    "There is an ocean of creativity within every human being.",  
    "Tenderness can be just as abstract as insanity.",  
    "I like darkness and confusion and absurdity, but I like to know that there could be a little door that you could go out into a safe life area of happiness.",  
    "Individual peace is the unit of world peace.",  
    "Inside, we are ageless and when we talk to ourselves, it’s the same age of the person we were talking to when we were little. It’s the body that is changing around that ageless center.",  
    "Directors who have inspired me include Billy Wilder, Federico Fellini, lngmar Bergman, John Ford, Orson Welles, Werner Herzog, Stanley Kubrick, Alfred Hitchcock, Francis Ford Coppola and Ernst Lubitsch. In art school, I studied painters like Edward Hopper, who used urban motifs, Franz Kafka is my favorite novelist. My approach to film stems from my art background, as I go beyond the story to the sub-conscious mood created by sound and images.",  
    "Many things happen that we don’t know the significance of until a little bit later.",  
    "I’m not a political person. I don’t understand politics, I don’t understand the concept of two sides and I think that probably there’s good on both sides, bad on both sides, and there’s a middle ground, but it never seems to come to the middle ground and it’s very frustrating watching it and seemingly we’re not moving forward.",  
    "I started Transcendental Meditation in 1973 and have not missed a single meditation ever since. Twice a day, every day. It has given me effortless access to unlimited reserves of energy, creativity, and happiness deep within.",  
    "Film noir has a mood that everyone can feel. It’s people in trouble, at night, with a little bit of wind and the right kind of music. It’s a beautiful thing.",  
    "Intuition is the key to everything, in painting, filmmaking, business – everything. I think you could have an intellectual ability, but if you can sharpen your intuition, which they say is emotion and intellect joining together, then a knowingness occurs.",  
    "There is an ocean of pure vibrant consciousness inside each one of us.",  
    "The only thing that disturbs me is that many psychopaths say they had a very happy childhood.",  
    "I love child things because there’s so much mystery when you’re a child. When you’re a child, something as simple as a tree doesn’t make sense. You see it in the distance and it looks small, but as you go closer, it seems to grow – you haven’t got a handle on the rules when you’re a child. We think we understand the rules when we become adults but what we really experienced is a narrowing of the imagination.",  
    "Intuition is knowingness, and this field of unbounded knowing, of knowingness, is within every human being. You start tapping into that and it becomes an ocean of solutions.",  
    "I like making films because I like to go into another world. I like to get lost into another world.",  
    "I learned that just beneath the surface there’s another world, and still different worlds as you dig deeper. I knew it as a kid, but I couldn’t find the proof. It was just a kind of feeling. There is goodness in blue skies and flowers, but another force – a wild pain and decay – also accompanies everything.",  
    "I just like going into strange worlds.",  
    "You need contrast and conflict in order to tell a story. Stories need to have dark and light, turmoil, all those things. But that does not mean the filmmaker has to suffer in order to show the suffering. Stories should have the suffering, not the people.",  
    "Life is very, very complicated, and so films should be allowed to be, too.",  
    "The cinema is really built for the big screen and big sound, so that a person can go into another world and have an experience.",  
    "Black has depth.. you can go into it.. And you start seeing what you’re afraid of. You start seeing what you love, and it becomes like a dream.",  
    "Life is filled with abstractions, and the only way to make heads or tails of it is going through intuition.",  
    "Stories have tangents; they open up and become different things. You can still have a structure, but you should leave room to dream. If you stay true to your ideas, filmmaking becomes an inside-out, honest kind of process. And if it’s an honest thing for you, there’s a chance that people will feel that, even if it’s abstract.",  
    "Meditation is not a selfish thing. Even though you’re diving in and experiencing the Self, you’re not closing yourself off from the world. You’re strengthening yourself, so that you can be more effective when you go back into the world.",  
    "I love seeing people come out of darkness.",  
    "If you have a golf-ball-sized consciousness, when you read a book, you’ll have a golf-ball-sized understanding; when you look out a window, a golf-ball-sized awareness, when you wake up in the morning, a golf-ball-sized wakefulness; and as you go about your day, a golf-ball-sized inner happiness. But if you can expand that consciousness, make it grow, then when you read about that book, you’ll have more understanding; when you look out, more awareness; when you wake up, more wakefulness; as you go about your day, more inner happiness.",
    "All my movies are about strange worlds that you can’t go into unless you build them and film them. That’s what’s so important about film to me. I just like going into strange worlds.",  
    "Sex is a doorway to something so powerful and mystical, but movies usually depict it in a completely flat way.",  
    "I discovered that if one looks a little closer at this beautiful world, there are always red ants underneath.",  
    "In the world there’s a thing called collective consciousness. All of us billions of human beings together create that collective consciousness. With all the problems in our world, you can see that the collective consciousness is not so high.",  
    "Stories always have held conflicts and contrasts, highs and lows, life and death situations. And there can be much suffering in stories, but now we say the artist doesn’t have to suffer to show suffering. You just have to understand the human condition, understand the suffering.",  
    "Through the darkness of future past, the magician longs to see, one chance out between two worlds, fire walk with me!",  
    "Intuition is the key to everything, in painting, filmmaking, business – everything. I think you could have an intellectual ability, but if you can sharpen your intuition, which they say is emotion and intellect joining together, then a knowingness occurs. Feeling correct is a feeling I think everyone knows.",  
    "There’s always fear of the unknown where there’s mystery.",  
    "I hate slick and pretty things. I prefer mistakes and accidents. Which is why I like things like cuts and bruises – they’re like little flowers. I’ve always said that if you have a name for something, like ‘cut’ or ‘bruise,’ people will automatically be disturbed by it. But when you see the same thing in nature, and you don’t know what it is, it can be very beautiful.",  
    "Every single thing in the world that was made by anyone started with an idea. So to catch one that is powerful enough to fall in love with, it is one of the most beautiful experiences. It’s like being jolted with electricity and knowledge at the same time.",  
    "Lately I feel films are more and more like music. Music deals with abstractions and, like film, it involves time. It has many different movements, it has much contrast. And through music you learn that, in order to get a particular beautiful feeling, you have to have started far back, arranging certain things in a certain way. You can’t just cut to it.",  
    "I like to remember things my own way. How I remembered them, not necessarily the way they happened.",  
    "You don’t dive for specific solutions; you dive to enliven that ocean of consciousness. Then your intuition grows and you have a way of solving those problems-knowing when it’s not quite right and knowing a way to make it feel correct for you. That capacity grows and things go much more smoothly.",  
    "A film is its own thing and in an ideal world I think a film should be discovered knowing nothing and nothing should be added to it and nothing should be subtracted from it.",  
    "The big treasury is an ocean of infinite creativity. It’s a creativity that creates everything that is a thing – it’s mighty powerful creativity.",  
    "Secrets and mysteries provide a beautiful corridor where you can float out. The corridor expands and many, many wonderful things can happen… I love the process of going into mystery."]

formatted_quotes = []
num = 92
for quote in quotes:
    formatted_quotes.append([num, quote])
    num += 1

with open('DL_quotes.csv', 'a', encoding='UTF8') as f:
    writer = csv.writer(f)
    writer.writerows(formatted_quotes)
